custom_guidelines:
  general:
    - name: "akshay general guideline"
      path: "./python_branch/python_checks.doc"
  per_language:
    java:
      name: "akshay java guideline"
      path: "./java_branch/java_guidelines.rtf"
dependency_check.enabled: true
exclude_draft_pr: false
exclude_files: "*.xml, *.json, *.properties, .gitignore, *.yml, *.md"
include_source_branches: "*"
include_target_branches: "*"
linters_feedback: true
post_changelist: true
post_description: true
secret_scanner_feedback: true
suggestion_mode: comprehensive
