custom_guidelines:
  general:
    - name: "general guideline large "
      path: "guidelines/large.txt"
      name: "Python general guideline binary data"
      path: "guidelines/binary.data"
  per_language:
    java:
      name: "Java guideline valid -1 "
      path: "java_guidelines.rtf"
    python:
      name: "Python long Guideline"
      path: "long_guideline.txt"
   #   name: "python guideline valid - 1 "
   #   path: "python_checks.doc"
dependency_check.enabled: yes
exclude_draft_pr: false
exclude_files: "*.xml, *.json, *.properties, .gitignore, *.yml, *.md, *.pdf, *.txt, *.doc"
include_source_branches: "*"
include_target_branches: "*"
linters_feedback: yes
post_changelist: true
post_description: true
secret_scanner_feedback: true
suggestion_mode: comprehensive
