1custom_guidelines:
  general:
    - name: ""
      path: ""
  per_language:
    java:
      name: "Java guideline valid -1 "
      path: "java_guidelines.rtf"
    python:
      name: "Python error_rules guideline"
      path: "guidelines/error_rules.txt"
      name: "Python function_rules guideline"
      path: "guidelines/function_rules.txt"
    python:
      name: "Python naming_rules guideline"
      path: "guidelines/naming_rules.txt"
1dependency_check.enabled: yes
1exclude_draft_pr: false
1exclude_files: "*.xml, *.json, *.properties, .gitignore, *.yml, *.md, *.pdf, *.txt, *.doc"
1include_source_branches: "*"
1include_target_branches: "*"
linters_feedback: yes
1post_changelist: true
1post_description: false
1secret_scanner_feedback: false
1suggestion_mode: comprehensive
