custom_guidelines:
  general:
    - name: "general guideline"
      path: "general_guidelines/general_guideline.pdf"
      name: "Python general guideline"
      path: "general_guideline/python/general_guideline.txt"
  per_language:
    java:
      name: "akshay java guideline"
      path: "java_guidelines.rtf"
      name: "akshay python guideline"
      path: "python_checks.doc"
dependency_check.enabled: true
exclude_draft_pr: false
exclude_files: "*.xml, *.json, *.properties, .gitignore, *.yml, *.md"
include_source_branches: "*"
include_target_branches: "*"
linters_feedback: true
post_changelist: true
post_description: true
secret_scanner_feedback: true
suggestion_mode: comprehensive
